// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Battery status and health information.
///
/// Provides real-time battery metrics including charge level, charging state,
/// and overall battery health assessment.
class BatteryInfo {
  /// Current battery charge level (0-100 percentage)
  final double? level;

  /// Whether the device is currently connected to power and charging
  final bool? isCharging;

  /// Battery health status (e.g., "Good", "Fair", "Poor")
  final String? health;

  const BatteryInfo({this.level, this.isCharging, this.health});

  @override
  int get hashCode => level.hashCode ^ isCharging.hashCode ^ health.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatteryInfo &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          isCharging == other.isCharging &&
          health == other.health;
}

/// Comprehensive device identification and hardware information.
///
/// Contains unique identifiers and basic hardware details that can be used
/// for device fingerprinting, analytics, or user identification.
class DeviceInfoResponse {
  /// Unique device identifier (Hardware UUID or GUID)
  final String? uuid;

  /// Device manufacturer (e.g., "Apple Inc.", "Dell Inc.")
  final String? manufacturer;

  /// Device model name (e.g., "MacBook Pro", "OptiPlex 7090")
  final String? model;

  /// Device serial number (may be restricted on some platforms)
  final String? serial;

  /// Android-specific device ID (Android only)
  final String? androidId;

  /// User-assigned device name (hostname)
  final String? deviceName;

  const DeviceInfoResponse({
    this.uuid,
    this.manufacturer,
    this.model,
    this.serial,
    this.androidId,
    this.deviceName,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      manufacturer.hashCode ^
      model.hashCode ^
      serial.hashCode ^
      androidId.hashCode ^
      deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfoResponse &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          manufacturer == other.manufacturer &&
          model == other.model &&
          serial == other.serial &&
          androidId == other.androidId &&
          deviceName == other.deviceName;
}

/// Display/screen properties and capabilities.
///
/// Contains information about the primary display including resolution,
/// scaling factor, and refresh rate.
class DisplayInfo {
  /// Screen width in physical pixels
  final int width;

  /// Screen height in physical pixels
  final int height;

  /// Display scale factor (e.g., 2.0 for Retina/HiDPI displays)
  final double scaleFactor;

  /// Screen refresh rate in Hz (e.g., 60.0, 120.0, 144.0)
  final double? refreshRate;

  const DisplayInfo({
    required this.width,
    required this.height,
    required this.scaleFactor,
    this.refreshRate,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      scaleFactor.hashCode ^
      refreshRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          scaleFactor == other.scaleFactor &&
          refreshRate == other.refreshRate;
}

/// Network connection details and identifiers.
///
/// Contains information about the current network connection including
/// IP address, connection type, and hardware address.
class NetworkInfo {
  /// Local IPv4 address (e.g., "192.168.1.100")
  final String? ipAddress;

  /// Connection type: "wifi", "ethernet", "cellular", or "unknown"
  final String? networkType;

  /// MAC address (unavailable on iOS/Android due to privacy restrictions)
  final String? macAddress;

  const NetworkInfo({this.ipAddress, this.networkType, this.macAddress});

  @override
  int get hashCode =>
      ipAddress.hashCode ^ networkType.hashCode ^ macAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkInfo &&
          runtimeType == other.runtimeType &&
          ipAddress == other.ipAddress &&
          networkType == other.networkType &&
          macAddress == other.macAddress;
}

/// Storage capacity and type information.
///
/// Provides information about the primary storage device including
/// total capacity, available space, and storage technology type.
class StorageInfo {
  /// Total storage capacity in bytes
  final BigInt totalSpace;

  /// Available (free) storage space in bytes
  final BigInt freeSpace;

  /// Storage technology type: "Ssd", "Hdd", "Removable", "Unknown"
  final String? storageType;

  const StorageInfo({
    required this.totalSpace,
    required this.freeSpace,
    this.storageType,
  });

  @override
  int get hashCode =>
      totalSpace.hashCode ^ freeSpace.hashCode ^ storageType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageInfo &&
          runtimeType == other.runtimeType &&
          totalSpace == other.totalSpace &&
          freeSpace == other.freeSpace &&
          storageType == other.storageType;
}
