// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run_blocking`

Future<DeviceInfoResponse> getDeviceInfo() =>
    RustLib.instance.api.crateApiDeviceInfoGetDeviceInfo();

Future<BatteryInfo> getBatteryInfo() =>
    RustLib.instance.api.crateApiDeviceInfoGetBatteryInfo();

Future<NetworkInfo> getNetworkInfo() =>
    RustLib.instance.api.crateApiDeviceInfoGetNetworkInfo();

Future<StorageInfo> getStorageInfo() =>
    RustLib.instance.api.crateApiDeviceInfoGetStorageInfo();

Future<DisplayInfo> getDisplayInfo() =>
    RustLib.instance.api.crateApiDeviceInfoGetDisplayInfo();
